---
- hosts: all
  #connection: local
  tasks:  
  
  - name: Who am i
    command: whoami
    register: result

  - debug: msg="{{ result.stdout }}"
  
  - name: Update packages
    yum:
      name: '*'
      state: latest
    register: result

  - debug: msg="{{ result.stdout }}"
