---
- hosts: all
  #connection: local
  tasks:
  - name: say hello
    debug:
      msg: "Hello World!"
  
  - name: Who am i
    command: whoami
    register: result
  - debug: msg="{{ result.stdout }}"
